2020-08-08 20:24:07,734 ERROR: Exception on /index [POST] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 35, in index
    db.session.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "D:\MicroBlog\app\models.py", line 114, in after_commit
    add_to_index(obj.__tablenmae__, obj)
AttributeError: 'Post' object has no attribute '__tablenmae__'
2020-08-08 20:25:19,134 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-08 20:27:41,522 ERROR: Exception on / [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 45, in index
    return render_template('index.html',
  File "d:\MicroBlog\micro\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "d:\MicroBlog\micro\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\MicroBlog\micro\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\MicroBlog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\MicroBlog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\MicroBlog\micro\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\MicroBlog\micro\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\MicroBlog\micro\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\MicroBlog\micro\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block "body"
    {% block scripts %}
  File "D:\MicroBlog\app\templates\base.html", line 67, in block "scripts"
    $(destElem).html('<img src="{{ url_for(static, filename='loading.gif') }}">');
  File "d:\MicroBlog\micro\lib\site-packages\flask\helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'static' is undefined
2020-08-08 20:28:02,527 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-08 20:54:19,501 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: cannot unpack non-iterable NoneType object
2020-08-08 20:55:23,782 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-08 20:55:34,898 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: cannot unpack non-iterable NoneType object
2020-08-08 20:57:29,828 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
