2020-08-06 21:11:19,617 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:25:13,596 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:26:45,520 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:27:01,787 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:27:36,449 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:54:23,231 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-06 21:57:05,524 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:77]
2020-08-07 22:44:18,012 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-07 22:44:21,043 ERROR: Exception on / [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "D:\MicroBlog\app\main\routes.py", line 18, in before_request
    db.session.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "D:\MicroBlog\app\models.py", line 118, in after_commit
    for obj in session.changes['delete']:
AttributeError: 'SignallingSession' object has no attribute 'changes'
2020-08-07 22:44:28,424 ERROR: Exception on /favicon.ico [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "D:\MicroBlog\app\main\routes.py", line 18, in before_request
    db.session.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 1042, in commit
    self.transaction.commit()
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\orm\session.py", line 511, in commit
    self.session.dispatch.after_commit(self.session)
  File "d:\MicroBlog\micro\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "D:\MicroBlog\app\models.py", line 118, in after_commit
    for obj in session.changes['delete']:
AttributeError: 'SignallingSession' object has no attribute 'changes'
2020-08-07 22:45:08,604 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-07 22:45:22,943 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablenmae__, expression, page, per_page)
AttributeError: type object 'Post' has no attribute '__tablenmae__'
2020-08-07 22:45:36,405 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablenmae__, expression, page, per_page)
AttributeError: type object 'Post' has no attribute '__tablenmae__'
2020-08-08 20:20:28,571 INFO: Microblog startup [in D:\MicroBlog\app\__init__.py:81]
2020-08-08 20:20:51,467 ERROR: Exception on /search [GET] [in d:\MicroBlog\micro\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\MicroBlog\micro\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\MicroBlog\micro\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\MicroBlog\micro\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\MicroBlog\app\main\routes.py", line 175, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "D:\MicroBlog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: cannot unpack non-iterable NoneType object
